#!/bin/bash
# wall-redirect daemon — turns a BLOCKED X / Instagram / Netflix visit into a
# bounce to the social wall, instead of a dead connection-error page. The urge
# to open a junk feed is redirected into the wall automatically.
#
# Runs as root via launchd (com.antifeed.wall-redirect) because it binds the
# privileged ports 80/443 on 127.0.0.1 — exactly where wall-gate points blocked
# domains (close_gates maps them to 127.0.0.1). So this only ever fires while a
# domain is BLOCKED. When the gate is OPEN (a collection sweep) the domains
# resolve to the REAL servers, nothing reaches 127.0.0.1, and CDP harvesting is
# completely untouched.
#
# Super-minimal by design: NO Node / Python / long-lived interpreter. Two socat
# listeners (a ~300KB C binary) each just fork a one-shot `printf` of a 302 per
# connection and exit; idle cost is a process blocked on accept(). HTTPS is
# mandatory because twitter/x/instagram are HSTS-preloaded — socat presents an
# mkcert-signed cert the system already trusts (generated by install-redirect.sh).
#
# NOTE: socat cannot inspect the requested Host, so EVERY blocked domain that
# resolves to 127.0.0.1 bounces to the wall and must be covered by the cert's
# SANs (see install-redirect.sh) — otherwise it would cert-error instead.
set -euo pipefail
export PATH=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin

DIR=/usr/local/etc/wall-redirect
CERT="$DIR/redirect.pem"
KEY="$DIR/redirect-key.pem"
WALL="https://social-wall-five.vercel.app/"

command -v socat >/dev/null 2>&1 || { echo "socat not found — brew install socat"; exit 1; }
[ -f "$CERT" ] && [ -f "$KEY" ] || { echo "cert missing at $DIR — run install-redirect.sh"; exit 1; }

# The 302 lives in a static file that socat just `cat`s to each connection.
# Do NOT inline it as printf in socat's SYSTEM address: socat mangles the \r\n
# escapes and the shell then splits the headers into separate commands. A file
# of exact bytes sidesteps all of socat's quoting/escape processing.
RESP_FILE="$DIR/302.http"
printf 'HTTP/1.1 302 Found\r\nLocation: %s\r\nContent-Length: 0\r\nCache-Control: no-store\r\nConnection: close\r\n\r\n' "$WALL" > "$RESP_FILE"

# :443 — TLS-terminated (required for the HSTS-preloaded domains).
socat OPENSSL-LISTEN:443,bind=127.0.0.1,reuseaddr,fork,cert="$CERT",key="$KEY",verify=0 SYSTEM:"/bin/cat $RESP_FILE" &
P443=$!
# :80 — plain, for the rare non-HTTPS hit.
socat TCP-LISTEN:80,bind=127.0.0.1,reuseaddr,fork SYSTEM:"/bin/cat $RESP_FILE" &
P80=$!

trap 'kill "$P443" "$P80" 2>/dev/null || true' TERM INT
# bash 3.2 has no `wait -n`: poll, and if either listener dies, exit so launchd
# (KeepAlive) restarts the whole daemon cleanly.
while kill -0 "$P443" 2>/dev/null && kill -0 "$P80" 2>/dev/null; do sleep 5; done
kill "$P443" "$P80" 2>/dev/null || true
exit 1
